version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: production_nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    networks:
      - backend
    depends_on:
      - cuizinart
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    expose:
       - '5432'
    networks:
       - backend

  cuizinart:
     build: 
       context: ./cuizinart
       args: 
         userid: ${USER_ID}
     restart: unless-stopped
     read_only: true  # make root fs read-only, but keep /tmp writable (for request files)
     tmpfs:
       - /tmp
     depends_on:
       - postgres
     env_file:
       - .env
     networks:
       - backend
     expose:
       - '5000'
     volumes:
       - ${NC_INPUT_PATH}:${NC_INPUT_PATH}
       - ${LOG_DIRECTORY}:${LOG_DIRECTORY}
       - ${SSH_KNOWN_HOSTS_PATH}:/home/gwf/.ssh/known_hosts
       - ${DB_MIGRATIONS_FOLDER}:/tmp/gwf/migrations
     security_opt:
       - no-new-privileges:true

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  pyspark:
    build: ./cuizinart_pyspark
    env_file:
      - .env
    environment:
      FLASK_APP: 'pyspark_app.py'
    expose:
      - '5001'
    networks:
      - backend
    volumes:
      - ${NC_INPUT_PATH}:${NC_INPUT_PATH}
      - ${NC_OUTPUT_PATH}:${NC_OUTPUT_PATH}
      - ${LOG_DIRECTORY}:${LOG_DIRECTORY}

networks:
  backend:
    driver: bridge

